#!/usr/bin/env bash
# nginx web server listening on port 80
# returns a page that contains the string "Hello World!"

sudo apt update -y
sudo apt install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "server {
        listen 80;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
}" > /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

nginx -s reload

exit 0
