#!/usr/bin/env bash
# script to add a permanent redirect to current server block
sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sudo sed -i '/^\s*location \/ {$/,/^\s*}/ s/^\s*}/\    return 301 https:\/\/gogoanime.cl/category/one-piece;\n}/' /etc/nginx/sites-available/default

sudo service nginx reload
