#!/usr/bin/env bash
# script to add a permanent redirect to current server block
sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sudo sed -i '/location \/ {/a \\n}\n\nif ($request_filename ~ redirect_me){\n    rewrite ^ https:\/\/gogoanime.cl\/category\/one-piece permanent;\n}\n' /etc/nginx/sites-available/default

sudo service nginx reload
