#!/usr/bin/env bash
# installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend abyhajon-frontend
        bind *:80
        mode http
        default_backend abyhajon-backend

backend abyhajon-backend
        balance roundrobin
        server 129285-web-01 100.26.217.138:80 check
        server 129285-web-02 35.168.3.232:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
