#!/usr/bin/env bash
#Script loops from from 1 t0 10 displaying
#Bad luck on the fourth loop
#good luck on the eighth loop
#Best school on the rest

n=0
while [ $n -lt 10 ]
do 
	if [ $n -eq 3 ]
	then
		echo "bad luck"
	elif [ $n -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
