#!/usr/bin/env bash
#This script prints different messages on the fourth and eighth iteration.
#the fourth prints "Bad luck"
#the fifth displays "Good luck"
#the rest prints "Best School"

count=0

while [ $count -lt 10 ]
do 
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
